name: Build, Push, and Update Manifest

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and Push Docker Image
      run: |
        docker buildx create --use
        docker buildx build -t kripu77/github-actions-ci-test:latest -f Dockerfile .
        docker push kripu77/github-actions-ci-test:latest
      # - name: Checkout Manifest Repository
      #   uses: actions/checkout@v2
      #   with:
      #     repository: your-docker-username/kubernetes-manifests
      #     path: path/to/kubernetes-manifests
  modifygit:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: changing the deployment of git repo
      with:
        repository: 'kripu77/helm-argocd'
        token: ${{ secrets.GIT_PASSWORD }}
    - name: modify the image
      run: |
        git config user.email ${{ secrets.GIT_EMAIL }}
        git config user.name ${{ secrets.GIT_USERNAME }}}
        pwd
        cd helm-chart
        pwd
        cat values.yaml
        pwd
        sed -i '/^app:/,/tag:/ s/tag:.*/tag: app-$RUN_NUMBER/' values.yaml
        cat values.yaml
        git add .
        git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
        git push origin main
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        RUN_NUMBER: ${{ github.run_number }}
